apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "koios-chart.fullname" . }}-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}